services:
  crawler:
    image: suhach0523/techeerism-crawler:$IMAGE_TAG
    networks:
      - main-network
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - RABBITMQ_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_PASSWORD=$RABBITMQ_DEFAULT_PASS
      - RABBITMQ_HOST=$RABBITMQ_HOST
      - TRACING_GRPC=$TRACING_GRPC
    tty: true
    deploy:
      replicas: $SERVICE_REPLICAS
      placement:
        constraints:
          - node.labels.instance == staging
      resources:
        limits:
          cpus: "0.8"
          memory: 800M
        reservations:
          cpus: "0.25"
          memory: 100MB
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        monitor: 15s
        order: start-first
      restart_policy:
        condition: any
        delay: 15s

networks:
  main-network:
    external: true