services:
  crawler:
    image: suhach0523/techeerism-crawler:$IMAGE_TAG
    networks:
      - main-network
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - RABBITMQ_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_PASSWORD=$RABBITMQ_DEFAULT_PASS
      - RABBITMQ_HOST=$RABBITMQ_HOST
    labels:
      - logging=promtail
      - logging_jobname=crawler
    restart: always
    tty: true
    deploy:
      replicas: $SERVICE_REPLICAS
      placement:
        constraints:
          - node.labels.instance == crawler
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        monitor: 15s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 30s
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-retries: "5"

networks:
  main-network:
    external: true