version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=false"
      - "--providers.docker=true" 
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=techeerism_main-network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=whysano517@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--accesslog.filepath=/traefik/logs/access.log"
      - "--accesslog.bufferingsize=100"
      - "--accesslog.format=json"
      - "--accesslog.fields.defaultmode=keep"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--accesslog.fields.headers.names.X-Forwarded-For=keep"
      - "--api.dashboard=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entryPoints.metrics.address=:8091"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8090
        published: 8090
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik-certificates:/letsencrypt"  
      - "traefik_logs:/traefik/logs/"
    networks:
      - main-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.instance == main
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mydashboard.rule=Host(`traefik.techeerzip.cloud`)"
        - 'traefik.http.routers.mydashboard.entrypoints=websecure'
        - "traefik.http.routers.mydashboard.service=api@internal"
        - "traefik.http.routers.mydashboard.tls.certresolver=letsencrypt"
        - "traefik.http.services.mydashboard.loadbalancer.server.port=8090"
        - "traefik.http.routers.mydashboard.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$s/8l8n86$$0l/9DjZD1w1SiwJCpZuhh0"

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.instance == main
      labels:
        - traefik.enable=true
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.http.routers.portainer.entrypoints=websecure
        - traefik.http.routers.portainer.rule=Host(`portainer.techeerzip.cloud`)
        - traefik.http.routers.portainer.tls.certresolver=letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - main-network

  nest:
    image: suhach0523/techeerism-nest:1.0.7
    networks:
      - main-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.instance == main
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.services.nest.loadbalancer.server.port=8000
        - traefik.http.routers.nest.entrypoints=websecure
        - traefik.http.routers.nest.rule=Host(`api.techeerzip.cloud`) && PathPrefix(`/api/v1`)
        - traefik.http.routers.nest.middlewares=nest-stripprefix
        - traefik.http.middlewares.nest-stripprefix.stripprefix.prefixes=/api/v1
        - traefik.http.routers.nest.tls.certresolver=letsencrypt

  # 모니터링 시각화
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.instance == monitoring
      labels:
        - traefik.enable=true
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.entrypoints=websecure
        - traefik.http.routers.grafana.tls.certresolver=letsencrypt
        - traefik.http.routers.grafana.rule=Host(`grafana.techeerzip.cloud`)
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - main-network

  # 모니터링 메트릭 데이터 수집
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    user: root
    networks:
      - main-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.instance == main
  
  # 컨터이너 메트릭 데이터 수집
  cadvisor:
    image: google/cadvisor:latest
    deploy:
      mode: global
    labels:
      - prometheus-job=cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - main-network
  
  # 호스트 메트릭 데이터 수집
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.8.1
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - main-network
    deploy:
      mode: global
    labels:
      - prometheus-job=node-exporter

  # 로그 수집
  promtail:
    image:  grafana/promtail:latest
    volumes:
      - ./promtail/config.yaml:/etc/promtail/docker-config.yaml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/GeoLite2-City.mmdb:/etc/promtail/GeoLite2-City.mmdb
      - traefik_logs:/traefik/logs/
    command:
      - -config.file=/etc/promtail/docker-config.yaml
      - -config.expand-env=true
    depends_on:
      - loki
    networks:
      - main-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.instance == main
  
  # 로그 저장
  loki:
    image: grafana/loki:latest
    # volumes:
    #   - ./loki/config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - main-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.instance == monitoring
    
networks:
  main-network:
    driver: overlay

volumes:
  traefik-certificates:
  portainer_data:
  grafana_data:
  traefik_logs: