services:
  nest:
    image: suhach0523/techeerism-nest:$IMAGE_TAG
    networks:
      - main-network
    deploy:
      replicas: $SERVICE_REPLICAS
      placement:
        constraints:
          - node.labels.instance == main
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.services.nest.loadbalancer.server.port=8000
        - traefik.http.routers.nest.entrypoints=websecure
        - traefik.http.routers.nest.rule=Host(`api.techeerzip.cloud`) && PathPrefix(`/api/v1`)
        - traefik.http.routers.nest.middlewares=nest-stripprefix
        - traefik.http.middlewares.nest-stripprefix.stripprefix.prefixes=/api/v1
        - traefik.http.routers.nest.tls.certresolver=letsencrypt

networks:
  main-network:
    external: true