services:
  parser:
    image: suhach0523/techeerism-parser:$IMAGE_TAG
    networks:
      - main-network
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - RABBITMQ_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_PASSWORD=$RABBITMQ_DEFAULT_PASS
      - RABBITMQ_HOST=$RABBITMQ_HOST
      - SEARCH_API_URL=$SEARCH_API_URL
      - AI_HOST_URL=$AI_HOST_URL
      - GOOGLE_AUTH_TYPE=$GOOGLE_AUTH_TYPE
      - GOOGLE_AUTH_PROJECT_ID=$GOOGLE_AUTH_PROJECT_ID
      - GOOGLE_AUTH_PRIVATE_KEY_ID=$GOOGLE_AUTH_PRIVATE_KEY_ID
      - GOOGLE_AUTH_PRIVATE_KEY=$GOOGLE_AUTH_PRIVATE_KEY
      - GOOGLE_AUTH_CLIENT_EMAIL=$GOOGLE_AUTH_CLIENT_EMAIL
      - GOOGLE_AUTH_CLIENT_ID=$GOOGLE_AUTH_CLIENT_ID
      - GOOGLE_AUTH_CLIENT_X509_CERT_URL=$GOOGLE_AUTH_CLIENT_X509_CERT_URL
    restart: always
    tty: true
    deploy:
      replicas: $SERVICE_REPLICAS
      placement:
        constraints:
          - node.labels.instance == parser
      resources:
        limits:
          cpus: "0.8"
          memory: 800M
        reservations:
          cpus: "0.25"
          memory: 100MB
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        monitor: 15s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 30s

networks:
  main-network:
    external: true