services:
  parser:
    image: suhach0523/techeerism-parser:$IMAGE_TAG
    networks:
      - main-network
    deploy:
      replicas: $SERVICE_REPLICAS
      placement:
        constraints:
          - node.labels.instance == parser
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        monitor: 15s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 30s

networks:
  main-network:
    external: true