global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100

  # - job_name: 'cadvisor'
  #   dns_sd_configs:
  #     - names:
  #         - 'tasks.cadvisor'
  #       type: 'A'
  #       port: 8090
