global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    dockerswarm_sd_configs:
      - role: 'service'
    relabel_configs:
      - source_labels: [__meta_docker_swarm_service_name]
        target_label: job
        replacement: 'node-exporter'

  - job_name: 'cadvisor'
    dockerswarm_sd_configs:
      - role: 'service'
    relabel_configs:
      - source_labels: [__meta_docker_swarm_service_name]
        target_label: job
        replacement: 'cadvisor'

  - job_name: 'docker_metrics'
    static_configs:
      - targets: ['host.docker.internal:9323']
