services:
  spring:
    image: suhach0523/techeerism-spring:$IMAGE_TAG
    networks:
      - main-network
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=$DATABASE_URL_SPRING
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_PASS=$EMAIL_PASS
      - JWT_SECRET=$SPRING_JWT_SECRET
      - SLACK=$SLACK_SECRET
      - RABBITMQ_HOST=$RABBITMQ_HOST
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
      - SWAGGER_USER=$SWAGGER_USER
      - SWAGGER_PASSWORD=$SWAGGER_PASSWORD
      - AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY
      - AWS_S3_SECRET_ACCESS_KEY=$AWS_S3_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME
      - AWS_REGION=$AWS_REGION
      - REDIS_URL=$REDIS_URL
      - GOOGLE_AUTH_TYPE=$GOOGLE_AUTH_TYPE
      - GOOGLE_AUTH_PROJECT_ID=$GOOGLE_AUTH_PROJECT_ID
      - GOOGLE_AUTH_PRIVATE_KEY_ID=$GOOGLE_AUTH_PRIVATE_KEY_ID
      - GOOGLE_AUTH_PRIVATE_KEY=$GOOGLE_AUTH_PRIVATE_KEY
      - GOOGLE_AUTH_CLIENT_EMAIL=$GOOGLE_AUTH_CLIENT_EMAIL
      - GOOGLE_AUTH_CLIENT_ID=$GOOGLE_AUTH_CLIENT_ID
      - GOOGLE_FOLDER_ID=$GOOGLE_FOLDER_ID
      - GOOGLE_ARCHIVE_FOLDER_ID=$ARCHIVE_FOLDER_ID
      - RABBITMQ_URL=$RABBITMQ_URL
      - SLACKBOT_URL=$SLACKBOT_URL
      - SLACKBOT_PERSONAL_URL=$SLACKBOT_PERSONAL_URL
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - PROJECT_NAME=$PROJECT_NAME
      - INDEX_API_URL=$INDEX_API_URL
      - TRACING_AGENT_URL=$TRACING_AGENT_URL
      - PROFILE_IMG_URL=$PROFILE_IMG_URL
      - HTTPS_SERVER_URL=$HTTPS_SERVER_URL # for swagger
      - STAGING_SERVER_URL=$STAGING_SERVER_URL #for swagger
      - OTEL_EXPORTER_OTLP_ENDPOINT=$TRACING_GRPC_SPRING
      - OTEL_SERVICE_NAME=techeerzip-spring
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - X_API_KEY=$X_API_KEY
      - TRACING_GRPC=TRACING_GRPC_SPRING     
      - ZOOM_API_ACCOUNT_ID=$ZOOM_API_ACCOUNT_ID
      - ZOOM_API_CLIENT_ID=$ZOOM_API_CLIENT_ID
      - ZOOM_API_CLIENT_SECRET=$ZOOM_API_CLIENT_SECRET
      - ZOOM_WEBHOOK_SECRET=$ZOOM_WEBHOOK_SECRET
      - ZOOM_WEBHOOK_VERIFICATION_TOKEN=$ZOOM_WEBHOOK_VERIFICATION_TOKEN
      - ZOOM_DEFAULT_MEETING_ID=$ZOOM_DEFAULT_MEETING_ID
      - GITHUB_API_TOKEN=$GITHUB_API_TOKEN
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2GB
        reservations:
          cpus: "1"
          memory: 512MB
      replicas: $SERVICE_REPLICAS
      placement:
        constraints:
          - node.labels.instance == staging
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 15s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        monitor: 15s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      labels:
        - traefik.enable=true
        - "traefik.constraint-label=main-stack"
        - traefik.http.services.spring-main.loadbalancer.server.port=8000
        - traefik.http.routers.spring-main.entrypoints=websecure
        - traefik.http.routers.spring-main.rule=Host(`api.techeerzip.cloud`) && PathPrefix(`/api/v3`)
        - traefik.http.routers.spring-main.tls.certresolver=letsencrypt
        - traefik.http.middlewares.ratelimit-middleware2-spring.ratelimit.average=10
        - traefik.http.middlewares.ratelimit-middleware2-spring.ratelimit.burst=20
        - traefik.http.routers.spring-main.middlewares=ratelimit-middleware2-spring

networks:
  main-network:
    external: true
