global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'searchContainer'
    static_configs:
      - targets: ['search-container:8080']
  - job_name: 'meilisearch'
    static_configs:
      - targets: ["meilisearch:7700"]
    authorization:
      credentials: <credentials>
  - job_name: 'node-exporter-home'
    static_configs:
      - targets: ["node-exporter:9100"]