http:
  routers:
    # mydashboard:
    #   rule: "Host(`traefik.techeerzip.cloud`)"
    #   service: "api@internal"
    #   entryPoints:
    #     - "websecure"
    #   tls:
    #     certResolver: "letsencrypt"

    # External API
    external-api:
      rule: "Host(`external.techeerzip.cloud`)"
      service: "external-api"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"

  services:
    external-api:
      loadBalancer:
        servers:
          - url: $HOME_SERVER_URL
