http:
  routers:
    mydashboard:
      rule: "Host(`traefik.techeerzip.cloud`)"
      service: "api@internal"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"

    # External API
    external-api:
      rule: "Host(`external.techeerzip.cloud`)"
      service: "external-api"
      entryPoints:
        - "websecure"

  services:
    external-api:
      loadBalancer:
        servers:
          - url: http://100.116.150.4:8085 # External API backend
