receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  logging: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, logging]
