server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: traefik_file
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik_file
          __path__: /traefik/logs/access.log

    pipeline_stages:
      - json:
          expressions:
            client_ip: "\"request_X-Real-Ip\""
      - geoip:
          db: /etc/promtail/GeoLite2-City.mmdb
          db_type: city
          source: client_ip
      - labels:
          client_ip: client_ip
          city_name: geoip_city_name
          country_name: geoip_country_name
          continent_name: geoip_continent_name
